# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aigc < Formula
  desc "AI Git Commit CLI tool"
  homepage "https://github.com/dacsang97/aigc"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dacsang97/aigc/releases/download/v0.0.5/aigc_Darwin_x86_64.tar.gz"
      sha256 "cbfd48ef3e61072c7b9832c4236439fead8a34a674a0858c40e151a1918f83ae"

      def install
        bin.install "aigc"
      end
    end
    on_arm do
      url "https://github.com/dacsang97/aigc/releases/download/v0.0.5/aigc_Darwin_arm64.tar.gz"
      sha256 "cd37604a949e741459eb4905ba98888df381e2cfb080e99f10683f8e46272ec8"

      def install
        bin.install "aigc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/aigc/releases/download/v0.0.5/aigc_Linux_x86_64.tar.gz"
        sha256 "b50147068da5ac6b271658494e969bb077691d40d84511ad9688270ca7e07fb9"

        def install
          bin.install "aigc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/aigc/releases/download/v0.0.5/aigc_Linux_arm64.tar.gz"
        sha256 "b317236b894f5df761f2909e5875039f8a2a23fa28485c3f4169a61abad9b5c7"

        def install
          bin.install "aigc"
        end
      end
    end
  end

  test do
    system "#{bin}/aigc --version"
  end
end
