# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ght < Formula
  desc "GHT CLI"
  homepage "https://github.com/dacsang97/ght"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dacsang97/ght/releases/download/v0.0.1/ght_Darwin_x86_64.tar.gz"
      sha256 "2992ff203a9f6c39eee39503d2488f650975e5c4de654ecb0c95816e2eecf672"

      def install
        bin.install "ght"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dacsang97/ght/releases/download/v0.0.1/ght_Darwin_arm64.tar.gz"
      sha256 "8cd308a45fecf22183f99d88e178b247ee88174402678a4e6f1693dac90aa92e"

      def install
        bin.install "ght"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dacsang97/ght/releases/download/v0.0.1/ght_Linux_x86_64.tar.gz"
      sha256 "ff60b6e1656ba1360b300d0042e30896da301a738bf01117d687388e21132da5"
      def install
        bin.install "ght"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dacsang97/ght/releases/download/v0.0.1/ght_Linux_arm64.tar.gz"
      sha256 "b3372f298f3ebf343aa2d8dbeeec602c72ccdcc750eb6d3dc79f0b4976029d08"
      def install
        bin.install "ght"
      end
    end
  end

  test do
    system "#{bin}/ght --version"
  end
end
