# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GnasTm < Formula
  desc "AI Git Commit CLI tool"
  homepage "https://github.com/dacsang97/gnas-tm-releases"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dacsang97/gnas-tm-releases/releases/download/v0.0.1/gnas-tm-releases_Darwin_x86_64.tar.gz"
      sha256 "bddc06d10ef8447fbf2028bfe4bb0bda4ca355b051d9059d3ec93956a243df3e"

      def install
        bin.install "gnas-tm"
      end
    end
    on_arm do
      url "https://github.com/dacsang97/gnas-tm-releases/releases/download/v0.0.1/gnas-tm-releases_Darwin_arm64.tar.gz"
      sha256 "9fd256e261b3acf5300b20ae5ed5db16c4744ff7ff7dab8f6c79f8938e55cfaf"

      def install
        bin.install "gnas-tm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/gnas-tm-releases/releases/download/v0.0.1/gnas-tm-releases_Linux_x86_64.tar.gz"
        sha256 "68194810347079c9304b5251ca86c2de1a79c0c55913ba349dce84d5a6a6f11c"

        def install
          bin.install "gnas-tm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/gnas-tm-releases/releases/download/v0.0.1/gnas-tm-releases_Linux_arm64.tar.gz"
        sha256 "efe3d0d1d089f0a6a14e82eca2582fd406d0df071dee280c65afcbf3b557eb6a"

        def install
          bin.install "gnas-tm"
        end
      end
    end
  end

  test do
    system "#{bin}/gnas-tm --version"
  end
end
