# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safaribooks < Formula
  desc "Download and generate an EPUB of your favorite Safari Books Online titles"
  homepage "https://github.com/dacsang97/safaribooks"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.3/safaribooks_Darwin_x86_64.tar.gz"
      sha256 "b73a815c9c880feea1e8224ecc742be4116bcf94085feb52b2c4a2bae4b92a66"

      def install
        bin.install "safaribooks"
      end
    end
    on_arm do
      url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.3/safaribooks_Darwin_arm64.tar.gz"
      sha256 "1bbd6c1fd0afc5affa99942ec4953e3abf68b3eb1649a77814d2975b949333dd"

      def install
        bin.install "safaribooks"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.3/safaribooks_Linux_x86_64.tar.gz"
        sha256 "1f36feec03a576c713a506e5b46f892616b0cc7a8137e745d63c8cbc8cc88bee"

        def install
          bin.install "safaribooks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.3/safaribooks_Linux_arm64.tar.gz"
        sha256 "ddaa4a843536335e4b0ed512ebbf9a0a735c02e17e0b8f0f681d085a352aa409"

        def install
          bin.install "safaribooks"
        end
      end
    end
  end

  test do
    system "#{bin}/safaribooks --version"
  end
end
