# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safaribooks < Formula
  desc "Download and generate an EPUB of your favorite Safari Books Online titles"
  homepage "https://github.com/dacsang97/safaribooks"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.1/safaribooks_Darwin_x86_64.tar.gz"
      sha256 "0cd0a3250cdce9659f9f97d7930abe1132c7ef3ec7257cdba12cd1ecc791eb44"

      def install
        bin.install "safaribooks"
      end
    end
    on_arm do
      url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.1/safaribooks_Darwin_arm64.tar.gz"
      sha256 "0010a23bb513f2713789fc5578782eee003e6b2b6f16dfc31c5f38e763126825"

      def install
        bin.install "safaribooks"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.1/safaribooks_Linux_x86_64.tar.gz"
        sha256 "a8131995db272b376f0e956a161469753a9d6791871c9dff04504979c39a68e7"

        def install
          bin.install "safaribooks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dacsang97/safaribooks/releases/download/v0.0.1/safaribooks_Linux_arm64.tar.gz"
        sha256 "29bf50b0fa08f30b0c03b3277254925bd44f1962e452e150fad81e66fa4da99f"

        def install
          bin.install "safaribooks"
        end
      end
    end
  end

  test do
    system "#{bin}/safaribooks --version"
  end
end
